# Data acquisition

The first step of the machine learning research pipeline is the
Data Acqusition step. Here the following tasks are undertaken:

- Local data source
- Load data source
- Check data integrity
- Review data structure
- Preview data

## Case-Study: Malta International Airport

Loading the [Malta International Airport](https://maltairport.com/) passenger movements statistical data in differet formats.

In [1]:
import pandas as pd
import os.path as osp 

#os.path is used to have an OS agnostic code, which runs on Windows, Linux and Mac.

In [2]:
# Load the MIA dataset
df = pd.read_csv(osp.join('..','data','mia','miaPassengers 01.csv'))

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        19 non-null     int64
 1   passengers  19 non-null     int64
dtypes: int64(2)
memory usage: 436.0 bytes

Either from the data dictirionary or by actually previewing the data file we get an indication of the number of rows and columns, to verify
with what has been loaded. Here we undertake a data integrity check and confirm that we have 19 rows, 2 columns, no nulls and two 64-bit integer variables. Next we preview the data to verify the start and end of the dataframe.

In [3]:
# Preview the start of the data
df.head() #the default value its 5 rows

   year  passengers
0  2005     2397049
1  2006     2696034
2  2007     2974501
3  2008     3109868
4  2009     2918664

In [4]:
# Preview the end of the data
df.tail() # the default value its 5 rows

    year  passengers
14  2019     7310289
15  2020     1748050
16  2021     2540335
17  2022     5851079
18  2023     7803042

Following a data integrity check we confirm that the data file was consistent, that no notes were added and no aggregrate info was appended to the end.

In [5]:
# Loaidng second file version
df = pd.read_csv(osp.join('..','data','mia','miaPassengers 02.csv'),sep=';')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        19 non-null     int64
 1   passengers  19 non-null     int64
dtypes: int64(2)
memory usage: 436.0 bytes

Either by prevwiinwg the method documetnation by hovering the cursro over the method or by visiting the documenation pandas website we understand proper method usage.

In [6]:
df = pd.read_csv(osp.join('..','data','mia','miaPassengers 02.csv'),sep=';')
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        19 non-null     int64
 1   passengers  19 non-null     int64
dtypes: int64(2)
memory usage: 436.0 bytes

   year  passengers
0  2005     2397049
1  2006     2696034
2  2007     2974501
3  2008     3109868
4  2009     2918664

In [7]:
df.tail(10) # change the number of rows outpputed from this function

    year  passengers
9   2014     4290304
10  2015     4618640
11  2016     5080071
12  2017     6014548
13  2018     6808177
14  2019     7310289
15  2020     1748050
16  2021     2540335
17  2022     5851079
18  2023     7803042

In [8]:
# laoding a text file with a tab as a seprator
df = pd.read_csv(osp.join('..','data','mia','miaPassengers.txt'),sep='\t')
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        19 non-null     int64
 1   passengers  19 non-null     int64
dtypes: int64(2)
memory usage: 436.0 bytes

   year  passengers
0  2005     2397049
1  2006     2696034
2  2007     2974501
3  2008     3109868
4  2009     2918664

In [9]:
df.tail()

    year  passengers
14  2019     7310289
15  2020     1748050
16  2021     2540335
17  2022     5851079
18  2023     7803042

In [10]:
# load the data from a json file
df = pd.read_json(osp.join('..','data','mia','miaPassengers.json'))
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        19 non-null     int64
 1   passengers  19 non-null     int64
dtypes: int64(2)
memory usage: 436.0 bytes

   year  passengers
0  2005     2397049
1  2006     2696034
2  2007     2974501
3  2008     3109868
4  2009     2918664

In [11]:
df.tail()

    year  passengers
14  2019     7310289
15  2020     1748050
16  2021     2540335
17  2022     5851079
18  2023     7803042

In [12]:
# Accessing a file using file locks to get variable names
with open(osp.join('..','data','mia','miaPassengers.names'),'r', encoding='utf-8-sig') as f:
    columns = f.read().strip().split(',')

columns

['year', 'passengers']

We created a pointer ```f``` to the file we wnat to access and attached a read lock. We also define the encoding, meaning the character space to use to interpret the context, utf8. the ```utf-8-sig``` variant is needed to support the specific BOM character of this file. Every file has a BOM and EOF character.

When reading the context of the file we remove whitespaces using the ```strip()``` method, then we create a list with the contents of the file using the ```split(',')``` mehtod since they are comma sepearted.

In [13]:
df = pd.read_csv(osp.join('..','data','mia','miaPassengers.data'),names=columns)
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        19 non-null     int64
 1   passengers  19 non-null     int64
dtypes: int64(2)
memory usage: 436.0 bytes

   year  passengers
0  2005     2397049
1  2006     2696034
2  2007     2974501
3  2008     3109868
4  2009     2918664

In [14]:
df.tail()

    year  passengers
14  2019     7310289
15  2020     1748050
16  2021     2540335
17  2022     5851079
18  2023     7803042

In [15]:
df = pd.read_excel(osp.join('..','data','mia','miaPassengers.xlsx'))

It appears that `read_excel` is dependent on another package `openpyxl`. Attempting to import thhat pickage directly results in an error indicating that it is not installed in our Virtual Enviormenanet. to install a package in your virtual envioremtn follow these steps:

    1.Search for the package on [PyPI](https://pypi.org)
    2.Check the python version compatibility
    3. To Verify your current python version you can either chekc the vesrion on your Kernel listing in vscode, alterniatvely in a Terminal/cmd
        prompt run `python --version` (for windows)
    4.To check the command needed for prior version the page will link in the previous Versions selection
    5. Copy the Command needed
    6. From VsCode open a new terminal and make sure the enviormnet is activated
    7.Run the command
    8.upon completion in vscode type CTRL+SHIFT+P then select `Developer:Reload Window`
    9. Re-run the script.